// File: Barrel_Shifter.v
// Generated by MyHDL 0.11.45
// Date: Tue Jul 30 19:58:05 2024


`timescale 1ns/10ps

module Barrel_Shifter (
    par_in,
    par_out,
    shift_amount
);
// A barrel shifter with 3-bits shift amount for 12-bits register.
// :param par_in: Parallel input (12-bits).
// :param par_out: Parallel output (12-bits).
// :param shift_amount: Amount of shift to be executed (3-bits maximum).

input [11:0] par_in;
output [11:0] par_out;
wire [11:0] par_out;
input [2:0] shift_amount;





assign par_out = (par_in >>> shift_amount);

endmodule
