// File: Not1.v
// Generated by MyHDL 0.11.45
// Date: Sun Jul 28 10:22:31 2024


`timescale 1ns/10ps

module Not1 (
    output,
    input1
);
// NOT gate
// output = NOT input1

output output;
wire output;
input input1;





assign output = (!input1);

endmodule
