// File: Simple_Memory.v
// Generated by MyHDL 0.11.45
// Date: Sun Apr 14 13:01:00 2024


`timescale 1ns/10ps

module Simple_Memory (
    clk,
    en,
    addr,
    din,
    dout
);
// This module represents a simple memory composed of 32 registers, each storing an 8-bit value.
// Parameters:
//     - clk: A clock signal that synchronizes the operations of the memory.
//     - en: A write enable signal, controlling whether data is written into the memory.
//     - addr: An address signal specifying the location to write data to or read data from.
//     - din: A data input signal carrying the information to be written into the memory.
//     - dout: A data output signal providing the data read from the memory.

input clk;
input en;
input [4:0] addr;
input [7:0] din;
output [7:0] dout;
wire [7:0] dout;

reg [7:0] mem [0:32-1];



always @(posedge clk) begin: SIMPLE_MEMORY_WRITE
    if (en) begin
        mem[addr] <= din;
    end
end



assign dout = mem[addr];

endmodule
