// File: fetch.v
// Generated by MyHDL 0.11.45
// Date: Tue Jul 30 19:51:10 2024


`timescale 1ns/10ps

module fetch (
    clk,
    instruction,
    fetched_instruction
);


input clk;
input [31:0] instruction;
output [31:0] fetched_instruction;
reg [31:0] fetched_instruction;




always @(posedge clk) begin: FETCH_LOGIC
    fetched_instruction <= instruction;
end

endmodule
