// File: counter.v
// Generated by MyHDL 0.11.45
// Date: Fri Apr 19 12:20:18 2024


`timescale 1ns/10ps

module counter (
    clk,
    rst,
    c_en,
    w_en,
    count,
    write_in
);


input clk;
input rst;
input c_en;
input w_en;
output [11:0] count;
reg [11:0] count;
input [11:0] write_in;




always @(posedge clk, negedge rst) begin: COUNTER_LOGIC
    if (rst == 0) begin
        count <= 0;
    end
    else begin
        if (w_en) begin
            count <= write_in;
        end
        else if (c_en) begin
            count <= (count + 1);
        end
        else begin
            count <= count;
        end
    end
end

endmodule
